name: Pages deploy
on:
  push:
    branches: ["main"]
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4' 
          bundler-cache: true
      - name: install jekyll
        run: bundle install
        working-directory: docs
      - name: build site
        run: bundle exec jekyll build
        working-directory: docs
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'
